name: Create executables

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  package:
    name: Create native packages
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Extract version from pom.xml
        id: extract_version
        shell: bash
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            pwsh -command '
              $version = Select-String -Pattern "<version>(.*)</version>" -InputObject (Get-Content pom.xml) | ForEach-Object { $_.Matches.Groups[1].Value }
              Write-Host "Extracted version: $version"
              Add-Content -Path $env:GITHUB_ENV -Value "version=$version"
            '
          else
            version=$(grep "<version>" pom.xml | head -n 1 | sed 's/.*<version>\(.*\)<\/version>.*/\1/')
            echo "Extracted version: $version"
            echo "version=$version" >> $GITHUB_ENV
          fi
      - name: Build application
        run: mvn -B package
      - name: Package application with jpackage
        shell: bash
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            pwsh -command '
              mkdir dist
              $app_version = $env:version -replace "-SNAPSHOT", ""
              $jpackage_cmd = "jpackage --type exe --input target/ --main-jar pexi-$($env:version).jar --name PEXI --app-version $app_version --vendor 'Henning Steinberg (drachenpapa)' --dest dist/"
              Write-Host "Running jpackage with command: $jpackage_cmd"
              Invoke-Expression $jpackage_cmd
            '
          else
            mkdir -p dist
            app_version=$(echo "$version" | sed 's/-SNAPSHOT//')
            if [[ "$RUNNER_OS" == "macos-latest" ]]; then
              jpackage \
                --type dmg \
                --input target/ \
                --main-jar pexi-${{ env.version }}.jar \
                --name PEXI \
                --app-version "$app_version" \
                --vendor "Henning Steinberg (drachenpapa)" \
                --dest dist/
            else
              jpackage \
                --type deb \
                --input target/ \
                --main-jar pexi-${{ env.version }}.jar \
                --name PEXI \
                --app-version "$app_version" \
                --vendor "Henning Steinberg (drachenpapa)" \
                --dest dist/
            fi
          fi
      - name: Upload packaged application
        uses: actions/upload-artifact@v4
        with:
          name: PEXI-${{ env.version }}-${{ matrix.os }}
          path: dist/
