name: Create Executable

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  package:
    name: Create Windows Executable
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Extract version from pom.xml
        id: extract_version
        run: |
          version=$(grep -oP '<version>\K[^<]+' pom.xml | head -n 1)
          version=$(echo "$version" | sed 's/-SNAPSHOT//')
          echo "Extracted version: $version"
          echo "version=$version" >> $GITHUB_ENV
      - name: Build the project
        run: mvn -B package
      - name: Package the application with jpackage
        run: |
          mkdir dist
          app_version=$version
          jpackage_cmd="jpackage --type exe --input target/ --main-jar pexi-$version.jar --name PEXI --app-version $app_version --vendor 'Henning Steinberg (drachenpapa)' --dest dist/"
          echo "Running jpackage with command: $jpackage_cmd"
          $jpackage_cmd
      - name: Upload packaged application
        uses: actions/upload-artifact@v4
        with:
          name: PEXI-${{ env.version }}-windows
          path: dist/
